repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v6.0.0
        hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
    -   repo: https://github.com/python-jsonschema/check-jsonschema
        rev: 0.31.0
        hooks:
            -   id: check-github-workflows
                args: [ "--verbose" ]
    -   repo: https://github.com/tox-dev/tox-ini-fmt
        rev: "1.5.0"
        hooks:
            -   id: tox-ini-fmt
                args: [ "-p", "lint" ]
    -   repo: https://github.com/tox-dev/pyproject-fmt
        rev: "v2.5.0"
        hooks:
            -   id: pyproject-fmt
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.15.2
      hooks:
          - id: ruff
          - id: ruff-format
            args:
                - --check
                - --config
                - ruff.toml
