# Generated by Django 5.2 on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharepoint_rest_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharepointtenant",
            name="client_cert_passphrase",
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name="Cert Passphrase"),
        ),
        migrations.AddField(
            model_name="sharepointtenant",
            name="client_cert_path",
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name="Cert Path"),
        ),
        migrations.AddField(
            model_name="sharepointtenant",
            name="client_cert_tenant",
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="Cert Tenant"),
        ),
        migrations.AddField(
            model_name="sharepointtenant",
            name="client_cert_thumbprint",
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name="Cert Thumbprint"),
        ),
        migrations.AddField(
            model_name="sharepointtenant",
            name="client_id",
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="Client ID"),
        ),
    ]
