# Generated by Django 5.2 on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharepoint_rest_api", "0002_sharepointtenant_client_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=36, verbose_name="Name")),
                ("source_id", models.CharField(max_length=36, verbose_name="Source ID")),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True, verbose_name="Description"),
                ),
                (
                    "default_filters",
                    models.JSONField(blank=True, default=dict, null=True, verbose_name="Default filters"),
                ),
            ],
            options={
                "verbose_name": "Source ID",
                "verbose_name_plural": "Source IDs",
                "ordering": ["name"],
            },
        ),
    ]
